---
title: "CarbonAnalysis"
author: "ikebenaka"
date: "2023-03-27"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(GGally)
library(lme4)
library(lmerTest)
library(car)
library(sjPlot)
library(performance)
library(Amelia)
library(mosaic)
library(Sleuth3)
library(car)
library(boot)
library(lmtest)
library(MASS)
library(AER)
library(pscl)
```

```{r}
soil <- read.csv("soil.csv")
soil <- soil %>%
  rename %>%
  mutate(soil = case_when(
    soil == "FF" ~ "Forest floor",
    soil == "MIN" ~ "Mineral soil",
    TRUE ~ soil)) %>%
  mutate(site = case_when(
    site == "P1" ~ "Plow 1",
    site == "P2" ~ "Plow 2",
    site == "S1" ~ "Pasture 1",
    site == "S2" ~ "Pasture 2",
    site == "W1" ~ "Woodlot 1",
    site == "W2" ~ "Woodlot 2",
    TRUE ~ site))


#Remove NAs
soil <- na.omit(soil)

#Factor classes
soil$stake <- as.factor(soil$stake)
soil$row <- as.factor(soil$row)
soil$site <- as.factor(soil$site)
```

```{r}
#Create a model --> carbon as dependent variable
sc1 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + ff.thickness + bulk.density + soil.mass + om+ph.h2o+n+p+nh4+no3+ca+mg+k + soil.moisture + soil.moisture.capacity + n.min+nitr + cec, data = soil)
summary(sc1)
sc2 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + bulk.density + om + ph.h2o + n + nh4 + soil.moisture, data = soil)
summary(sc2)
sc3 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + bulk.density + om + ph.h2o + n + soil.moisture, data = soil)
summary(sc3)
sc4 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + bulk.density + om + ph.h2o + n, data = soil)
summary(sc4)
sc5 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + om + ph.h2o + n, data = soil)
summary(sc5)
sc6 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc6)

AIC(sc1,sc2,sc3,sc4,sc5,sc6) #sc4 with lowest AIC
lrtest(sc1,sc2,sc3,sc4,sc5,sc6) #sc4 fits the data equally well as the full model, sc6 fits data as well as sc5
vif(sc4)
vif(sc6)
```

```{r}
ggplot(soil, aes(x=site,y=c))+
  geom_boxplot()
```

