## Effects of Land Use on Soil Moisture

```{r}
#Load packages
library(ggplot2)
library(GGally)
library(lme4)
library(dplyr)
library(lmerTest)
```


```{r}
soil <- read.csv("soil.csv")
soil <- soil %>%
  #select(-row, -stake) %>%
  rename %>%
  mutate(soil = case_when(
    soil == "FF" ~ "Forest floor",
    soil == "MIN" ~ "Mineral soil",
    TRUE ~ soil)) %>%
  mutate(site = case_when(
    site == "P1" ~ "Plow 1",
    site == "P2" ~ "Plow 2",
    site == "S1" ~ "Pasture 1",
    site == "S2" ~ "Pasture 2",
    site == "W1" ~ "Woodlot 1",
    site == "W2" ~ "Woodlot 2",
    TRUE ~ site))

#Remove NAs
soil <- na.omit(soil)
#soil <- drop_na(soil$soil.moisture)
soil$stake <- as.factor(soil$stake)
soil$row <- as.factor(soil$row)
soil$site <- as.factor(soil$site)

#Visualize data
ggpairs(soil, c("site", "row", "stake", "soil", "soil.mass", "soil.moisture", "soil.moisture.capacity"))

#Count unique values for each variable
sapply(lapply(soil, unique), length)
  #soil variable only has one unique value (Forest floor) --> drop from model

#Create a model --> soil moisture as dependent variable
smois <- lmer(soil.moisture ~ factor(site) + (1|row) + (1|stake) + ff.thickness + bulk.density + soil.mass + ph.h2o + ph.cacl2 + c + n + om + p + nh4 + no3 + n.min + nitr + cec + ca + mg + k + soil.moisture + soil.moisture.capacity, data = soil)
summary(smois)
  #random effects
    #standard deviation -->  This is a measure of the variability for each random effect that you added to the model
    #row, stake -->effect of row/stake, overall variation within row/stake, gives us the variance...std. dev. is the effect size (effect of row/stake on overall soil moisture)
   #Residual --> stands for the variability that’s not due to either stake or row
    #row effect is greater than stake --> looking at std. dev. to determine this
  #fixed effects
    #coefficients --> represent the slope for the categorical effect of soil data
    #t- value --> simply the estimate divided by the standard error
    #intercept = the average of our data for the Pasture 1 location condition
plot(smois)

#Assumptions: creating a residual plot, a histogram of the residuals or a Q-Q plot 

#Best Model
smois2 <- lmer(soil.moisture ~ factor(site) + (1|row) + (1|stake) + ff.thickness + soil.moisture.capacity, data = soil)
summary(smois2)
plot(smois2)

AIC(smois, smois2)
library(car)
vif(smois2)

library(ggplot2)
ggplot(soil, aes(x=factor(site), y=soil.moisture)) +
  geom_point() +
  geom_smooth(se = FALSE, method = lm) +
  theme_bw() 


ggplot(soil, aes(x=factor(site), y=soil.moisture)) +
  geom_boxplot() +
  geom_smooth(se = FALSE, method = lm) +
  theme_bw()

#Mean of soil moisture for each of the land use types
soil %>% filter(site == "Plow 1" | site == "Plow 2") %>%
  summarise(mean=mean(soil.moisture))
  #0.9737

soil %>% filter(site == "Pasture 1" | site == "Pasture 2") %>%
  summarise(mean=mean(soil.moisture))
  #1.238039	

soil %>% filter(site == "Woodlot 1" | site == "Woodlot 2") %>%
  summarise(mean=mean(soil.moisture))
  #1.604906	
```

