---
title: "ENV 710: Final Project"
author: "Isabel Zungailia, Li Jia Go, Isaac Benaka, Katie Owens"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE)

#Packages

```

## Soil Moisture
```{r}
soil <- read.csv("soil.csv")
soil <- soil %>%
  #select(-row, -stake) %>%
  rename %>%
  mutate(soil = case_when(
    soil == "FF" ~ "Forest floor",
    soil == "MIN" ~ "Mineral soil",
    TRUE ~ soil)) %>%
  mutate(site = case_when(
    site == "P1" ~ "Plow 1",
    site == "P2" ~ "Plow 2",
    site == "S1" ~ "Pasture 1",
    site == "S2" ~ "Pasture 2",
    site == "W1" ~ "Woodlot 1",
    site == "W2" ~ "Woodlot 2",
    TRUE ~ site))

#Remove NAs
soil <- na.omit(soil)
#soil <- drop_na(soil$soil.moisture)
soil$stake <- as.factor(soil$stake)
soil$row <- as.factor(soil$row)
soil$site <- as.factor(soil$site)

#Visualize data
ggpairs(soil, c("site", "row", "stake", "soil", "soil.mass", "soil.moisture", "soil.moisture.capacity"))

#Count unique values for each variable
sapply(lapply(soil, unique), length)
  #soil variable only has one unique value (Forest floor) --> drop from model

#Create a FULL model --> soil moisture as dependent variable
smois1 <- lmer(soil.moisture ~ factor(site) + (1|row) + (1|stake) + ff.thickness + bulk.density + soil.mass + ph.h2o + ph.cacl2 + c + n + om + p + nh4 + no3 + n.min + nitr + cec + ca + mg + k + soil.moisture + soil.moisture.capacity, data = soil)
summary(smois1)
plot(smois1)

smois2 <- update(smois, .~. -bulk.density)
summary(smois2)

smois3 <- update(smois2, .~. -cec)
summary(smois3)

smois4 <- update(smois3, .~. -n.min)
summary(smois4)

smois5 <- update(smois4, .~. -nitr)
summary(smois5)

smois6 <- update(smois5, .~. -k)
summary(smois6)

smois7 <- update(smois6, .~. -c)
summary(smois7)

smois8 <- update(smois7, .~. -no3)
summary(smois8)

smois9 <- update(smois8, .~. -p)
summary(smois9)

smois10 <- update(smois9, .~. -om)
summary(smois10)

smois11 <- update(smois10, .~. -ph.cacl2)
summary(smois11)

smois12 <- update(smois11, .~. -ca)
summary(smois12)

smois13 <- update(smois12, .~. -mg)
summary(smois13)

smois14 <- update(smois13, .~. -nh4)
summary(smois14)

smois15 <- update(smois14, .~. -ph.h2o)
summary(smois15)

smois16 <- update(smois15, .~. -soil.mass)
summary(smois16)

smois17 <- update(smois16, .~. -n)
summary(smois17)

#Compare models with AIC
AIC(smois1, smois2, smois3, smois4, smois5, smois6, smois7, smois8, smois9, smois10, smois11, smois12, smois13, smois14, smois15, smois16, smois17)
  #smois17 is the best model

#Best Model
smois <- lmer(soil.moisture ~ factor(site) + (1|row) + (1|stake) + ff.thickness + soil.moisture.capacity, data = soil)
summary(smois)

## Check Assumptions

#Plot residuals
par(mfrow = c(2,2))
plot(smois)

#Check for heteroscedasticity
vif(smois)

MuMIn::r.squaredGLMM(smois) #final model has r-squared value of 0.594, meaning the model accounts for 59.4% of the variance in the response variable.

plot_model(smois)

#Diagnostics
check_model(smois, check = c("vif", "qq"))
check_model(smois, check = c("outliers"))
check_model(smois, check = c("reqq"))

#Site vs soil moisture (scatterplot)
ggplot(soil, aes(x=factor(site), y=soil.moisture)) +
  geom_point() +
  geom_smooth(se = FALSE, method = lm) +
  theme_bw() 

#Site vs soil moisture (boxplot)
ggplot(soil, aes(x=factor(site), y=soil.moisture)) +
  geom_boxplot() +
  geom_smooth(se = FALSE, method = lm) +
  theme_bw() + 
  labs(x="Site (Land Use Type)", y="Soil Moisture (gH20/gsoil)")

#Mean of soil moisture for each of the land use types
soil %>% filter(site == "Plow 1" | site == "Plow 2") %>%
  summarise(mean=mean(soil.moisture))
  #0.9737

soil %>% filter(site == "Pasture 1" | site == "Pasture 2") %>%
  summarise(mean=mean(soil.moisture))
  #1.238039	

soil %>% filter(site == "Woodlot 1" | site == "Woodlot 2") %>%
  summarise(mean=mean(soil.moisture))
  #1.604906	
```

```{r}
#Dataset for only Woodlot 1 and Woodlot 2
woodlot1 <- soil %>%
    filter(site %in% c("Woodlot 1"))

woodlot2 <- soil %>%
    filter(site %in% c("Plow 1"))

#Forest floor thickness vs soil moisture for Woodlot 1 & 2 

ggplot(woodlot1, aes(x=ff.thickness, y=soil.moisture)) +
  geom_point() +
  geom_smooth(se = FALSE, method = lm) +
  theme_bw() +ylab("Soil Moisture (gH20/gsoil)") + xlab("Woodlot 1 - Forest Floor Thickness (mm)")

ggplot(woodlot2, aes(x=ff.thickness, y=soil.moisture)) +
  geom_point() +
  geom_smooth(se = FALSE, method = lm) +
  theme_bw() +ylab("Soil Moisture") + xlab("Forest Floor Thickness (mm)")
```

```{r}
# Graph: Forest Floor Thickness X Soil Moisture
cfsmois <- fixef(smois)
with(soil, plot(ff.thickness, soil.moisture, pch=21, bg="white", main = "Relationship between Forest Floor Thickness and Soil Moisture by Colonial Land Use Type",
xlab = "Forest Floor Thickness (mm)",
ylab = "Soil Moisture (gH20/gsoil)", las = 1))
x <- seq(min(soil$ff.thickness), max(soil$ff.thickness), length=1000)

curve(cfsmois[1] + cfsmois[7]*x + cfsmois[8]*mean(soil$soil.moisture.capacity), add=T, col="orange", lwd = 1)  
# Pasture 1
curve(cfsmois[1] + cfsmois[2] + cfsmois[7]*x + cfsmois[8]*mean(soil$soil.moisture.capacity), add=T, col="purple", lwd = 1) 
# Pasture 2
curve(cfsmois[1] + cfsmois[3] + cfsmois[7]*x + cfsmois[8]*mean(soil$soil.moisture.capacity), add=T, col="green", lwd = 1) 
# Plow 1
curve(cfsmois[1] + cfsmois[4] + cfsmois[7]*x + cfsmois[8]*mean(soil$soil.moisture.capacity), add=T, col="blue", lwd = 1) 
# Plow 2
curve(cfsmois[1] + cfsmois[5] + cfsmois[7]*x + cfsmois[8]*mean(soil$soil.moisture.capacity), add=T, col="red", lwd = 1) 
# Woodlot 1
curve(cfsmois[1] + cfsmois[6] + cfsmois[7]*x + cfsmois[8]*mean(soil$soil.moisture.capacity), add=T, col="black", lwd = 1)
# Woodlot 2

LU <- c("Pasture 1", "Pasture 2", "Plow 1", "Plow 2", "Woodlot 1", "Woodlot 2")
Cols <- c("orange", "purple", "green", "blue", "red", "black")
legend("topleft", cex=0.75, LU, lty=1, col=Cols, lwd = 1)
```
## Soil Nitrogen Content

```{r}
soil <- read.csv("soil.csv")
soil <- soil %>%
  rename %>%
  mutate(soil = case_when(
    soil == "FF" ~ "Forest floor",
    soil == "MIN" ~ "Mineral soil",
    TRUE ~ soil)) %>%
  mutate(site = case_when(
    site == "P1" ~ "Plow 1",
    site == "P2" ~ "Plow 2",
    site == "S1" ~ "Pasture 1",
    site == "S2" ~ "Pasture 2",
    site == "W1" ~ "Woodlot 1",
    site == "W2" ~ "Woodlot 2",
    TRUE ~ site))

#Remove NAs
soil <- na.omit(soil)

#ggpairs(soil, c("site", "row", "stake", "soil", "soil.mass", "soil.moisture", "c","n","ph.h2o","om")) 

#Factor classes
soil$stake <- as.factor(soil$stake)
soil$row <- as.factor(soil$row)
soil$site <- as.factor(soil$site)

#full model to determine what impacts nitrogen in soils across the various plots 
n2.1 <- lmer(n ~ factor(site) + (1|row) + (1|stake) + ff.thickness + bulk.density + soil.mass + ph.h2o + ph.cacl2 + c  + om + p + nh4 + no3 + n.min + nitr + cec + ca + mg + k + soil.moisture + soil.moisture.capacity, data = soil)
summary(n2.1)

#stepwise reduction to remove the most non-significant factor
n2.2 <- update(n2.1, .~. -p)
summary(n2.2)

n2.3 <- update(n2.2, .~. -cec)
summary(n2.3)

n2.4 <- update(n2.3, .~. -k)
summary(n2.4)

n2.5 <- update(n2.4, .~. -mg)
summary(n2.5)

n2.6 <- update(n2.5, .~. -ph.cacl2)
summary(n2.6)

n2.7 <- update(n2.6, .~. -n.min)
summary(n2.7)

n2.8 <- update(n2.7, .~. -nh4)
summary(n2.8)

n2.9 <- update(n2.8, .~. -ff.thickness)
summary(n2.9)

n2.10 <- update(n2.9, .~. -nitr)
summary(n2.10)

n2.11 <- update(n2.10, .~. -no3)
summary(n2.11)

n2.12 <- update(n2.11, .~. -ph.h2o)
summary(n2.12)

n2.13 <- update(n2.12, .~. -soil.moisture.capacity)
summary(n2.13)

n2.14 <- update(n2.13, .~. -om)
summary(n2.14)

n2.15 <- update(n2.14, .~. -soil.moisture)
summary(n2.15)

#best model
n2.16 <- update(n2.15, .~. -bulk.density)
summary(n2.16)

AIC(n2.1, n2.2, n2.3, n2.4, n2.5, n2.6, n2.7, n2.8, n2.9, n2.10, n2.11, n2.12, n2.13, n2.14, n2.15, n2.16)

#variance
vif(n2.16)

#checking assumptions 
plot(n2.16)
#residual vs fitted plot looks ok.

#r2
MuMIn::r.squaredGLMM(n2.16)
```

```{r, graphing results}


plot_model(n2.16, sort.est = T, vline.color = "darkblue")

#graph of individual variables
cf.n <- fixef(n2.16)

#n vs c
with(soil, plot(c, n, pch=21, bg="white", main = "Relationship between Carbon and Nitrogen by \n Colonial Land Use Type",
xlab = "Percent Carbon",
ylab = "Percent Nitrogen", las = 1))
x <- seq(min(soil$c), max(soil$c), length=1000)

curve(cf.n[1] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*x + cf.n[9]*mean(soil$ca) , add=T, col="orange", lwd = 1)  
# Pasture 1
curve(cf.n[1] + cf.n[2] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*x + cf.n[9]*mean(soil$ca), add=T, col="purple", lwd = 1) 
# Pasture 2
curve(cf.n[1] + cf.n[3] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*x + cf.n[9]*mean(soil$ca), add=T, col="green", lwd = 1) 
# Plow 1
curve(cf.n[1] + cf.n[4] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*x + cf.n[9]*mean(soil$ca), add=T, col="blue", lwd = 1) 
# Plow 2
curve(cf.n[1] + cf.n[5] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*x + cf.n[9]*mean(soil$ca), add=T, col="red", lwd = 1)
# Woodlot 1
curve(cf.n[1] + cf.n[6] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*x + cf.n[9]*mean(soil$ca), add=T, col="black", lwd = 1) 
# Woodlot 2

LU <- c("Pasture 1", "Pasture 2", "Plow 1", "Plow 2", "Woodlot 1", "Woodlot 2")
Cols <- c("orange", "purple", "green", "blue", "red", "black")
legend("topleft", cex=0.6, LU, lty=1, col=Cols, lwd = 1)

#n vs ca
with(soil, plot(ca, n, pch=21, bg="white", main = "Relationship between Calcium (mg/g) and \nPercent Nitrogen by Colonial Land Use Type",
xlab = "Calcium (mg/g)",
ylab = "Percent Nitrogen", las = 1))
x <- seq(min(soil$ca), max(soil$ca), length=1000)

curve(cf.n[1] + cf.n[7]*mean(soil$soil.mass) + cf.n[8]*mean(soil$c) + cf.n[9]*x , add=T, col="orange", lwd = 1)  
# Pasture 1
curve(cf.n[1] + cf.n[2] +  cf.n[7]*mean(soil$soil.mass) + cf.n[8]*mean(soil$c) + cf.n[9]*x , add=T, col="purple", lwd = 1) 
# Pasture 2
curve(cf.n[1] + cf.n[3] +  cf.n[7]*mean(soil$soil.mass) + cf.n[8]*mean(soil$c) + cf.n[9]*x , add=T, col="green", lwd = 1) 
# Plow 1
curve(cf.n[1] + cf.n[4] +  cf.n[7]*mean(soil$soil.mass) + cf.n[8]*mean(soil$c) + cf.n[9]*x , add=T, col="blue", lwd = 1) 
# Plow 2
curve(cf.n[1] + cf.n[5] +  cf.n[7]*mean(soil$soil.mass) + cf.n[8]*mean(soil$c) + cf.n[9]*x , add=T, col="red", lwd = 1)
# Woodlot 1
curve(cf.n[1] + cf.n[6] +  cf.n[7]*mean(soil$soil.mass) + cf.n[8]*mean(soil$c) + cf.n[9]*x , add=T, col="black", lwd = 1) 
# Woodlot 2

LU <- c("Pasture 1", "Pasture 2", "Plow 1", "Plow 2", "Woodlot 1", "Woodlot 2")
Cols <- c("orange", "purple", "green", "blue", "red", "black")
legend("bottomright", cex=0.6, LU, lty=1, col=Cols, lwd = 1)


```
## Soil Carbon Content

```{r, data wrangling and exploration, include=F, echo=F}
soil <- read.csv("soil.csv")
soil <- soil %>%
  rename %>%
  mutate(soil = case_when(
    soil == "FF" ~ "Forest floor",
    soil == "MIN" ~ "Mineral soil",
    TRUE ~ soil)) %>%
  mutate(site = case_when(
    site == "P1" ~ "Plow 1",
    site == "P2" ~ "Plow 2",
    site == "S1" ~ "Pasture 1",
    site == "S2" ~ "Pasture 2",
    site == "W1" ~ "Woodlot 1",
    site == "W2" ~ "Woodlot 2",
    TRUE ~ site))

#Remove NAs
soil <- na.omit(soil)

#Factor classes
soil$stake <- as.factor(soil$stake)
soil$row <- as.factor(soil$row)
soil$site <- as.factor(soil$site)

ggpairs(soil, c("site", "row", "stake", "soil", "soil.mass", "soil.moisture", "c","n","ph.h2o","om"))

```

```{r, minimum adequate model, include=F, echo=F}
sc1 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + ff.thickness + bulk.density + soil.mass + om+ph.h2o+n+p+nh4+no3+ca+mg+k + soil.moisture + soil.moisture.capacity + n.min+nitr + cec, data = soil)
summary(sc1)
sc2 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + bulk.density + om + ph.h2o + n + nh4 + soil.moisture, data = soil)
summary(sc2)
sc3 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + bulk.density + om + ph.h2o + n + soil.moisture, data = soil)
summary(sc3)
sc4 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + bulk.density + om + ph.h2o + n, data = soil)
summary(sc4)
sc5 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + om + ph.h2o + n, data = soil)
summary(sc5)
sc6 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc6)

lrtest(sc1,sc2,sc3,sc4,sc5,sc6,sc7) #sc4 fits the data equally well as the full model, sc6 fits data as well as sc5

```

```{r, check transformations, include=F, echo=F}
#sc9 and sc12 look a little better

sc7 <- lmer(log(c) ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc7)

sc8 <- lmer(asin(sqrt(c/100)) ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc8)

sc9 <- lmer((c)^2 ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc9)

sc10 <- lmer(log10(max(c+1)-c) ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc10)

sc11 <- lmer(c^3 ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc11)

sc12 <- lmer(sqrt(max(c+1) - c) ~ factor(site) + (1|row) + (1|stake) + om + n, data = soil)
summary(sc12)

AIC(sc1,sc2,sc3,sc4,sc5,sc6,sc7,sc8,sc9,sc10,sc11,sc12)
lrtest(sc1,sc2,sc3,sc4,sc5,sc6,sc7,sc8,sc9,sc10,sc11,sc12)

check_model(sc6)
check_model(sc7)
check_model(sc8)
check_model(sc9)
check_model(sc10)
check_model(sc11)
check_model(sc12)

```

```{r, standardize, include=F, echo=F}
soil_s <- soil %>%
  mutate(n_s = scale(n))%>%
  mutate(om_s = scale(om))

#final model
sc13 <- lmer(c ~ factor(site) + (1|row) + (1|stake) + om_s + n_s, data = soil_s)
summary(sc13)
check_model(sc13)

MuMIn::r.squaredGLMM(sc13) #final model has r-squared value of 0.871, meaning the model accounts for 87% of the variance in the response variable.

```

```{r, plots, include=F, echo=F}
ggplot(soil, aes(x=site,y=c))+
  geom_boxplot()+
  labs(x="Colonial Land Use Type", y="Percent Carbon in Soil")

plot_model(sc13, sort.est = T, vline.color = "darkblue")

# Graph: OM X C
cf <- fixef(sc6)
with(soil, plot(om, c, pch=21, bg="white", main = "Relationship between Organic Matter and Carbon Content by Colonial Land Use Type",
xlab = "Percent Organic Matter",
ylab = "Percent Carbon", las = 1))
x <- seq(min(soil$om), max(soil$om), length=1000)
curve(cf[1] + cf[7]*x + cf[8]*mean(soil$n), add=T, col="orange", lwd = 1)  
# Pasture 1
curve(cf[1] + cf[2] + cf[7]*x + cf[8]*mean(soil$n), add=T, col="purple", lwd = 1) 
# Pasture 2
curve(cf[1] + cf[3] + cf[7]*x + cf[8]*mean(soil$n), add=T, col="green", lwd = 1) 
# Plow 1
curve(cf[1] + cf[4] + cf[7]*x + cf[8]*mean(soil$n), add=T, col="blue", lwd = 1) 
# Plow 2
curve(cf[1] + cf[5] + cf[7]*x + cf[8]*mean(soil$n), add=T, col="red", lwd = 1) 
curve(cf[1] + cf[6] + cf[7]*x + cf[8]*mean(soil$n), add=T, col="black", lwd = 1) 
LU <- c("Pasture 1", "Pasture 2", "Plow 1", "Plow 2", "Woodlot 1", "Woodlot 2")
Cols <- c("orange", "purple", "green", "blue", "red", "black")
legend("topleft", cex=0.75, LU, lty=1, col=Cols, lwd = 1)

#Graph: N X C
with(soil, plot(n, c, pch=21, bg="white", main = "Relationship between Nitrogen and Carbon Content by Colonial Land Use Type",
xlab = "Percent Nitrogen",
ylab = "Percent Carbon", las = 1))
x <- seq(min(soil$n), max(soil$n), length=1000)
curve(cf[1] + cf[7]*mean(soil$om) + cf[8]*x, add=T, col="orange", lwd = 1)  
# Pasture 1
curve(cf[1] + cf[2] + cf[7]*mean(soil$om) + cf[8]*x, add=T, col="purple", lwd = 1) 
# Pasture 2
curve(cf[1] + cf[3] + cf[7]*mean(soil$om) + cf[8]*x, add=T, col="green", lwd = 1) 
# Plow 1
curve(cf[1] + cf[4] + cf[7]*mean(soil$om) + cf[8]*x, add=T, col="blue", lwd = 1) 
# Plow 2
curve(cf[1] + cf[5] + cf[7]*mean(soil$om) + cf[8]*x, add=T, col="red", lwd = 1) 
curve(cf[1] + cf[6] + cf[7]*mean(soil$om) + cf[8]*x, add=T, col="black", lwd = 1) 
LU <- c("Pasture 1", "Pasture 2", "Plow 1", "Plow 2", "Woodlot 1", "Woodlot 2")
Cols <- c("orange", "purple", "green", "blue", "red", "black")
legend("topleft", cex=0.6, LU, lty=1, col=Cols, lwd = 1)

```












\pagebreak


***


## Appendix 

```{r ref.label=knitr::all_labels(), echo = T, eval = F}
``` 


-->